version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
    restart: unless-stopped

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOSTNAME: LOCAL_PUBLIC_IP
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9095,OUTSIDE://LOCAL_PUBLIC_IP:9092
      KAFKA_LISTENERS: INSIDE://:9095,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - "kafka"
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
     - KAFKA_CLUSTERS_0_NAME=local
     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9095
     - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  # 1 volume for 1 cluster
volumes:
  esdata:
    driver: local

    
